version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - "{{ jenkins_master_ip.stdout }}:8080:8080"
      - "{{ jenkins_master_ip.stdout }}:5000:5000"
    volumes:
      - "{{ jenkins_master_home }}:/var/jenkins_home"